### ISSUE TITLE
Softlock before night service

### ISSUE THREAD

**Issue by RobertoDeLaNoche** [denikson/COM3D2.MaidFiddler#10] opened 2018-12-22 21:32 UTC
**Describe the bug**
Black screen before entering Night Service, just before selecting the skills. the top right corner buttons are still active but the others don't work they just make the sound when the cursor cross them over. The console reads the following :
MissingFieldException: Field '.Data.conditionDatas' not found.
Stack trace:
YotogiSkillListManager.CreateDatas (MaidStatus.Status status, Boolean specialConditionCheck, SpecialConditionType type)
YotogiSkillSelectManager.OnCall ()
WfScreenChildren.Call ()
WfScreenManager.RunScreen (System.String screen_name)
WfScreenManager.Update ()
YotogiManager.Update ()

**To Reproduce**
I don't remember exactly, but i checked some boxes that were not (some not even translated) in the "Yotogi Skills" section, and changed a maid's personnality from "Innocent" to "Pure".

**Expected behavior**
Welp, I guessed it had to work as it always did ? I changed back everything that i touched, without success, additionally, the softlock happens whatever maid i pick, even if I did not change any of their's option.

**Screenshots**
![image](https://user-images.githubusercontent.com/46075702/50378685-48279680-0638-11e9-8ce5-e0e011283504.png)

**Version info (please complete the following information):**
 - COM3D2 1.19.1
 - CM3D2 1.62.0
(some of my maids have been transferred from CM3D2, including the one I have changed)
 - Maid Fiddler : GUI 1.0.4.1
                          Core : 1.0.4.0

**Additional context**
I guessed you tried to warn me that the game could softlock itself by manipulating higgledy-piggledy MaidFiddler, and of course I didn't backup or anything ...
Going through Night Service using the "Scene Replay" works just fine.

**Comment by denikson** [comment] 2018-12-22 21:36
Greetings!

Thank you for this very extensive information; this helps a lot.

Maid Fiddler 1.0.3.3 and newer require you to have COM3D2 1.23 or newer (this is apparent from the changelogs in the installer). 
Unfortunately, currently Maid Fiddler does not check your game version automatically: this will be addressed in the future.

For now, I suggest you either update your game (and update all other plugins you have) or downgrade Maid Fiddler to 1.0.3.2.

**Comment by RobertoDeLaNoche** [comment] 2018-12-22 21:43
Hey ! Thanks for this super duper fast answer !
I desperately tried to reboot my computer, didn't repaired the thing.
I'm gonna try what you said, i was not even aware that newer versions were out ! I just started the 1.6 Go downloading for version 1.24 . I'll come back to you when it is done !
Thanks again !

**Comment by denikson** [comment] 2018-12-22 21:48
You are most welcome! 

As a side note, editing yotogi skills directly via the "yotogi skills" tab has a potential danger of enabling skills that a certain personality cannot use. If you have a suspicion that such a mistake happened, you can use `All maids > Remove invalid yotogi skills` to have Maid Fiddler automatically remove invalid skills.

**Comment by RobertoDeLaNoche** [comment] 2018-12-22 21:55
oh ! thanks a lot ! I'll try this right now, the update will finish dowloading very soon so if what you just told me does not work either, i'll just update my game.

**Comment by RobertoDeLaNoche** [comment] 2018-12-22 21:58
Unfortunately, it didn't fix the problem, so i'll update my game to 1.24

**Comment by denikson** [comment] 2018-12-22 21:58
I'm mainly telling this as a note for the future. That said, if you want to unlock all skills, I suggest using the options in the `All maids` or `Selected maid` option, as those will take care of invalid skills automatically.

The issue you have is solely caused by incompatibility of the game and Maid Fiddler versions. So you will have to update nonetheless.

**Comment by RobertoDeLaNoche** [comment] 2018-12-22 22:12
Phew ! Ok, so i just updated COM3D2 and took the latest version of Sybaris and everything is back to normal. I am deeply sorry, and ashamed, I just wasted your time, but thank you soooo much for helping such a dumb guy as me ! I'll keep in mind to not touch anything with MaidFiddler and make a backup, like, right the f now !
Keep the good work out there, and once again thank you so much for everything !
(I hope this issue will help some other lost souls in the future)
Have a stupendous day !

**Comment by denikson** [comment] 2018-12-22 22:16
> I'll keep in mind to not touch anything with MaidFiddler

That's what Maid Fiddler is for, though 😄. What would be the point of me making Maid Fiddler if you weren't allowed to touch anything? Just keep some backups (as the warning message implies), and you're going to be fine.

In any case, you are most welcome! I'm closing this issue for now. If you have any new problems not related to this particular issue, do make a new issue ticket.

**Closed by denikson** 2018-12-22 22:16 UTC
